version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  ecma_version = "2016"
  module_system = "es-modules"
  environment = [
    "nodejs",
    "browser",
    "jest",
    "mocha"
  ]
  plugins = ["react"]
  
  dependency_file_paths = [
  "frontend/package.json",
  "backend/package.json",
  ]
